# Generated by Django 3.2.9 on 2021-12-09 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BookCab', '0002_alter_booking_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='BookCab.cabgroup'),
        ),
    ]
